name: qibo-benchmark-qibo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - psutil>=5.9.0
  - pytest>=7.4.0
  - black>=23.0.0
  - flake8>=6.0.0
  - isort>=5.12.0
  - pip:
    - qibo>=0.2.21